name: CI/CI pipeline
on:
  pull-request:
    branches: ['master']

jobs:
  CI:
    name: Continous Integraiton
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checar cÃ³digo
        uses: actions/checkout@v4 # Clona o repositÃ³rio para ter acesso a pasta do projeto no servidor

      - name: ğŸ› ï¸ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.13.0' #Instala versÃ£o do node
      - name: Instalar dependÃªncias
        run: npm install

      - name: ğŸ§ª Executar testes
        run: npm run test

       - name: ğŸ§ª Construir
        run: npm run build

  CD:
    name: Continuous Deploy
    runs-on: ubuntu-latest
    needs: CI
      - uses: actions/checkout@v4
      - name: ğŸ“‚ Install Vercel CLI
        run: npm install --global vercel@latest
      - name: ğŸ“© Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: ğŸ—ï¸ Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}


